### ISSUE TITLE
Incompatible with anything but Node.js 4.x

### ISSUE THREAD

**Issue by kasperisager** [bloomberg/wsk#5]
The only supported version of Node.js is currently 4.x:

https://github.com/bloomberg/wsk/blob/b3a845765ff2a01d20a9c10944356c4bef5653db/package.json#L30-L32

...preventing me from installing wsk under Node.js 8.x. Is this on purpose?

**Comment by mhkeller** [comment]
Thanks I’ll change that to a `>`. Out of curiosity, are you using `enginesStrict` in your main package.json? Normally it will still install.

**Comment by kasperisager** [comment]
Thanks! Might have something to do with me using Yarn instead of npm.

**Comment by mhkeller** [comment]
Give 1.0.1 a try, now on npm.
